// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dojo_survey.Models;

namespace dojo_survey.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191014200711_YourMigrationName")]
    partial class YourMigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dojo_survey.Models.User", b =>
                {
                    b.Property<int>("UerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("commentField")
                        .IsRequired();

                    b.Property<string>("favorLanguage")
                        .IsRequired();

                    b.Property<string>("nameField")
                        .IsRequired();

                    b.Property<string>("selectLocation")
                        .IsRequired();

                    b.HasKey("UerID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
